services:
  zipkin-server:
    container_name: zipkin-server
    image: openzipkin/zipkin:2.23
    mem_limit: 300m
    ports:
      - "9411:9411"
    networks:
      currency_network:

networks:
  currency_network: