spring:
  application:
    name: currency-exchange-service

  jpa:
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}

resilience4j:
  retry:
    instances:
      sample-api:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true

  ratelimiter:
    instances:
      default:
        limit-for-period: 2
        limit-refresh-period: 10s

  bulkhead:
    instances:
      default:
        max-concurrent-calls: 10
      sample-api:
        max-concurrent-calls: 10

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "health,info,metrics,loggers"


server:
  port: 8000
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [${spring.application.name:},%X{traceId:-},%X{spanId:-}] %logger{36} - %msg%n"

