spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: file:///home/haris/IdeaProjects/SpringBootMicroservices101/SpringBoot-Microservices-101/git-local-config-repo

server:
  port: 8889

